/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'ScheduleMsg'
 * message type.
 */

public class ScheduleMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 28;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 144;

    /** Create a new ScheduleMsg of size 28. */
    public ScheduleMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new ScheduleMsg of the given data_length. */
    public ScheduleMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ScheduleMsg with the given data_length
     * and base offset.
     */
    public ScheduleMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ScheduleMsg using the given byte array
     * as backing store.
     */
    public ScheduleMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ScheduleMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public ScheduleMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ScheduleMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public ScheduleMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ScheduleMsg embedded in the given message
     * at the given base offset.
     */
    public ScheduleMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ScheduleMsg embedded in the given message
     * at the given base offset and length.
     */
    public ScheduleMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <ScheduleMsg> \n";
      try {
        s += "  [msgid=0x"+Long.toHexString(get_msgid())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [left=0x"+Long.toHexString(get_left())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [schedule=";
        for (int i = 0; i < 26; i++) {
          s += "0x"+Long.toHexString(getElement_schedule(i) & 0xff)+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: msgid
    //   Field type: short, unsigned
    //   Offset (bits): 0
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'msgid' is signed (false).
     */
    public static boolean isSigned_msgid() {
        return false;
    }

    /**
     * Return whether the field 'msgid' is an array (false).
     */
    public static boolean isArray_msgid() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'msgid'
     */
    public static int offset_msgid() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'msgid'
     */
    public static int offsetBits_msgid() {
        return 0;
    }

    /**
     * Return the value (as a short) of the field 'msgid'
     */
    public short get_msgid() {
        return (short)getUIntBEElement(offsetBits_msgid(), 8);
    }

    /**
     * Set the value of the field 'msgid'
     */
    public void set_msgid(short value) {
        setUIntBEElement(offsetBits_msgid(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'msgid'
     */
    public static int size_msgid() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'msgid'
     */
    public static int sizeBits_msgid() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: left
    //   Field type: short, unsigned
    //   Offset (bits): 8
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'left' is signed (false).
     */
    public static boolean isSigned_left() {
        return false;
    }

    /**
     * Return whether the field 'left' is an array (false).
     */
    public static boolean isArray_left() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'left'
     */
    public static int offset_left() {
        return (8 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'left'
     */
    public static int offsetBits_left() {
        return 8;
    }

    /**
     * Return the value (as a short) of the field 'left'
     */
    public short get_left() {
        return (short)getUIntBEElement(offsetBits_left(), 8);
    }

    /**
     * Set the value of the field 'left'
     */
    public void set_left(short value) {
        setUIntBEElement(offsetBits_left(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'left'
     */
    public static int size_left() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'left'
     */
    public static int sizeBits_left() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: schedule
    //   Field type: short[], unsigned
    //   Offset (bits): 16
    //   Size of each element (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'schedule' is signed (false).
     */
    public static boolean isSigned_schedule() {
        return false;
    }

    /**
     * Return whether the field 'schedule' is an array (true).
     */
    public static boolean isArray_schedule() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'schedule'
     */
    public static int offset_schedule(int index1) {
        int offset = 16;
        if (index1 < 0 || index1 >= 26) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 8;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'schedule'
     */
    public static int offsetBits_schedule(int index1) {
        int offset = 16;
        if (index1 < 0 || index1 >= 26) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 8;
        return offset;
    }

    /**
     * Return the entire array 'schedule' as a short[]
     */
    public short[] get_schedule() {
        short[] tmp = new short[26];
        for (int index0 = 0; index0 < numElements_schedule(0); index0++) {
            tmp[index0] = getElement_schedule(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'schedule' from the given short[]
     */
    public void set_schedule(short[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_schedule(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a short) of the array 'schedule'
     */
    public short getElement_schedule(int index1) {
        return (short)getUIntBEElement(offsetBits_schedule(index1), 8);
    }

    /**
     * Set an element of the array 'schedule'
     */
    public void setElement_schedule(int index1, short value) {
        setUIntBEElement(offsetBits_schedule(index1), 8, value);
    }

    /**
     * Return the total size, in bytes, of the array 'schedule'
     */
    public static int totalSize_schedule() {
        return (208 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'schedule'
     */
    public static int totalSizeBits_schedule() {
        return 208;
    }

    /**
     * Return the size, in bytes, of each element of the array 'schedule'
     */
    public static int elementSize_schedule() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'schedule'
     */
    public static int elementSizeBits_schedule() {
        return 8;
    }

    /**
     * Return the number of dimensions in the array 'schedule'
     */
    public static int numDimensions_schedule() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'schedule'
     */
    public static int numElements_schedule() {
        return 26;
    }

    /**
     * Return the number of elements in the array 'schedule'
     * for the given dimension.
     */
    public static int numElements_schedule(int dimension) {
      int array_dims[] = { 26,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

    /**
     * Fill in the array 'schedule' with a String
     */
    public void setString_schedule(String s) { 
         int len = s.length();
         int i;
         for (i = 0; i < len; i++) {
             setElement_schedule(i, (short)s.charAt(i));
         }
         setElement_schedule(i, (short)0); //null terminate
    }

    /**
     * Read the array 'schedule' as a String
     */
    public String getString_schedule() { 
         char carr[] = new char[Math.min(net.tinyos.message.Message.MAX_CONVERTED_STRING_LENGTH,26)];
         int i;
         for (i = 0; i < carr.length; i++) {
             if ((char)getElement_schedule(i) == (char)0) break;
             carr[i] = (char)getElement_schedule(i);
         }
         return new String(carr,0,i);
    }

}
